package main

import (
	"donkey/config"
	"donkey/logger"
	"donkey/middleware"
	"donkey/routes"
	"fmt"
	"log/slog"
	"os"
	"path"

	"github.com/gofiber/swagger"
	maps "golang.org/x/exp/maps"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/basicauth"
	"github.com/gofiber/fiber/v2/middleware/compress"
	"github.com/gofiber/fiber/v2/middleware/cors"
	slogfiber "github.com/samber/slog-fiber"

	"github.com/gofiber/fiber/v2/middleware/recover"
	_ "github.com/joho/godotenv/autoload"

	// 	// docs are generated by Swag CLI, you have to import them.
	// // replace w``ith your own docs folder, usually "github.com/username/reponame/docs"

	_ "donkey/docs"
)

var (
	slogger *slog.Logger
)

func init() {
	// Load .env file

	// Make sure that the base directory exists
	if err := os.MkdirAll(config.AppConf.Dir, os.ModePerm); err != nil {
		slog.Error("Couldn't create the directory", err)
	}

	// Make sure that the base directory exists
	if err := os.MkdirAll(path.Join(config.AppConf.Dir, "thumbnails"), os.ModePerm); err != nil {
		slog.Error("Couldn't create thumbnails directory", err)
	}

	for _, user := range config.AppConf.Users {
		for _, folder := range maps.Keys(user.AccessPaths) {
			slog.Debug("Creting user folder " + folder + " if it doesn't exist")
			if err := os.MkdirAll(path.Join(config.AppConf.Dir, folder), os.ModePerm); err != nil {
				slog.Error("Couldn't create thumbnails directory", err)
			}
		}
	}

	slogger = logger.Logger()
}

// @title			Donkey API
// @version		1.0
// @description	This is a swagger representation of the application's API
// @termsOfService	http://swagger.io/terms/
// @contact.name	API Support
// @contact.email	vk@cloudnation.dk
// @license.name	MIT
// @license.url	./LICENSE
// @host			localhost:8080
// @BasePath		/api/v1
func main() {
	app := fiber.New(fiber.Config{
		AppName:   "Donkey v1.0.0",
		BodyLimit: 50 * 1024 * 1024,
		// Disable the default startup message
		DisableStartupMessage: true,
		// StreamRequestBody:            true,
		// If run with the following param the list of routes will be printed in the log when starting the server
		// EnablePrintRoutes: true,
	})

	app.Use(recover.New())
	// app.Use(csrf.New(csrf.Config{
	// 	KeyLookup:      "header:X-Csrf-Token",
	// 	CookieName:     "csrf_",
	// 	CookieSameSite: "Lax",
	// 	Expiration:     1 * time.Hour,
	// 	KeyGenerator:   utils.UUIDv4,
	// }))
	app.Use(compress.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins:     "http://localhost:5173/",
		AllowHeaders:     "Cache-Control, Accept-Encoding, Origin, Content-Type, Accept, Token, Content-Length, Accept-Encoding, X-Csrf-Token, Authorization",
		AllowCredentials: true,
		AllowMethods:     "GET, HEAD, PUT, PATCH, POST, DELETE",
		MaxAge:           0,
	}))

	app.Get("/swagger/*", swagger.HandlerDefault) // default

	app.Get("/swagger/*", swagger.New(swagger.Config{ // custom
		URL:         "http://example.com/doc.json",
		DeepLinking: false,
		// Expand ("list") or Collapse ("none") tag groups by default
		DocExpansion: "none",
		// Prefill OAuth ClientId on Authorize popup
		OAuth: &swagger.OAuthConfig{
			AppName:  "OAuth Provider",
			ClientId: "21bb4edc-05a7-4afc-86f1-2e151e4ba6e2",
		},
		// Ability to change OAuth2 redirect uri location
		OAuth2RedirectUrl: "http://localhost:8080/swagger/oauth2-redirect.html",
	}))

	// pass the custom logger through the fiber context
	app.Use(slogfiber.New(slogger))

	api_v1 := app.Group("/api/v1")
	api_v1.Post("/login", basicauth.New(basicauth.Config{
		Authorizer: func(username string, password string) bool {
			user, err := config.AppConf.FindStructByName(username)
			if err != nil {
				return false
			}
			return user.Password == password
		},
	}), routes.Login)
	api_v1.Get("/download/*", middleware.TokenMiddleware, routes.DownloadFile)
	api_v1.Get("/list/*", middleware.TokenMiddleware, routes.ListFiles)
	api_v1.Post("/upload/*", middleware.TokenMiddleware, routes.SaveFile)
	api_v1.Delete("/delete/*", middleware.TokenMiddleware, routes.DeleteFiles)
	api_v1.Get("/user/*", middleware.TokenMiddleware, routes.GetUser)
	api_v1.Post("/index/*", middleware.TokenMiddleware, routes.Index)

	admin_v1 := api_v1.Group("/admin")
	admin_v1.Get("/users", middleware.AdminMiddleware, routes.UsersList)
	admin_v1.Post("/user", middleware.AdminMiddleware, routes.UserCreate)
	admin_v1.Put("/user", middleware.AdminMiddleware, routes.UserUpdate)
	admin_v1.Delete("/user", middleware.AdminMiddleware, routes.UserDelete)
	admin_v1.Get("/config", middleware.AdminMiddleware, routes.GetConfig)
	admin_v1.Post("/config", middleware.AdminMiddleware, routes.UpdateConfig)

	slog.Debug("Starting the web-server!")

	app.Hooks().OnListen(func(listenData fiber.ListenData) error {

		// ASCII generated with
		// https://www.asciiart.eu/text-to-ascii-art
		// Font: Ghost
		// http://www.jave.de/figlet/fonts/details/ghost.html

		fmt.Println("\n" +
			" _ .-') _                    .-') _ .-. .-')     ('-.\n" +
			"( (  OO) )                  ( OO ) )\\  ( OO )  _(  OO)\n" +
			" \\     .'_  .-'),-----. ,--./ ,--,' ,--. ,--. (,------. ,--.   ,--.\n" +
			" ,`'--..._)( OO'  .-.  '|   \\ |  |\\ |  .'   /  |  .---'  \\  `.'  /\n" +
			" |  |  \\  '/   |  | |  ||    \\|  | )|      /,  |  |    .-')     /\n" +
			" |  |   ' |\\_) |  |\\|  ||  .     |/ |     ' _)(|  '--.(OO  \\   /\n" +
			" |  |   / :  \\ |  | |  ||  |\\    |  |  .   \\   |  .--' |   /  /\n" +
			" |  '--'  /   `'  '-'  '|  | \\   |  |  |\\   \\  |  `---.`-./  /\n" +
			" `-------'      `-----' `--'  `--'  `--' '--'  `------'  `--'\n" +
			" ")
		slog.Info("To connect to the server use => http://" + listenData.Host + ":" + listenData.Port)
		return nil
	})

	err := app.Listen(":" + config.AppConf.Port)
	if err != nil {
		slog.Error("Couldn't start the fiber server", err)
	}
}
