POST http://localhost:8080/api/v1/login HTTP/1.1
Authorization:	Basic dGVzdDp0ZXN0


###
GET http://localhost:8080/api/v1/list/banana HTTP/1.1
Token: admin


###
GET http://localhost:8080/api/v1/list/banana?token=admin HTTP/1.1
Token: admin

###
GET http://localhost:8080/api/v1/download/banana/mages.PNG HTTP/1.1
Token: admin

###
GET http://localhost:8080/api/v1/download/thumbnails/IMG_20210429_183514.jpg HTTP/1.1
Token: admin


###
POST http://localhost:8080/api/v1/index/banana HTTP/1.1
Token: admin